# Generated by Django 3.0.8 on 2020-08-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_urls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLs',
        ),
    ]
